name: example_io
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  my_conditional_lib:
    path: ../my_conditional_lib/
