name: sample_dart_cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  args: ^2.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
