name: example_html
description: An example of web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  my_conditional_lib:
    path: ../my_conditional_lib/

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6
